// Datos extraídos de la hoja "Base locales" (columnas A, B, C, E, F)
const localesMostaza = [
    { sigla: "MDB", local: "Dolores", provincia: "Buenos Aires", gerenteZona: "Yesica Zarate", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MQM", local: "Jumbo Quilmes", provincia: "Buenos Aires", gerenteZona: "Yesica Zarate", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MLP", local: "La Plata", provincia: "Buenos Aires", gerenteZona: "Yesica Zarate", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MAU", local: "Auchan", provincia: "Buenos Aires", gerenteZona: "Yesica Zarate", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MVA", local: "Varela", provincia: "Buenos Aires", gerenteZona: "Yesica Zarate", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MTR", local: "Trelew", provincia: "Chubut", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MMA", local: "Puerto Madryn", provincia: "Chubut", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MCA", local: "Carr Avellaneda", provincia: "Buenos Aires", gerenteZona: "Yesica Zarate", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MOC", local: "Madero 2", provincia: "Buenos Aires", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MPD", local: "Madero 3", provincia: "Buenos Aires", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MAA", local: "Alto Avellaneda", provincia: "Buenos Aires", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "AFA", local: "American Favs", provincia: "Buenos Aires", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MWC", local: "Walmart Comodoro", provincia: "Chubut", gerenteZona: "Bruno Ureta", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MCC", local: "Comodoro Centro", provincia: "Chubut", gerenteZona: "Damian Riquelme", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MPL", local: "Portal Lomas", provincia: "Buenos Aires", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MBO", local: "Boulevard", provincia: "Buenos Aires", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MLO", local: "Lomitas", provincia: "Buenos Aires", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MLT", local: "Las Toscas", provincia: "Buenos Aires", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MBB", local: "Bahia Blanca", provincia: "Buenos Aires", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MCP", local: "Patio Olmos", provincia: "Cordoba", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "MCL", local: "Cordoba Libertad", provincia: "Cordoba", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "MCG", local: "General Paz", provincia: "Cordoba", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "MCV", local: "Villa Cabrera", provincia: "Cordoba", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "MJC", local: "Jockey", provincia: "Cordoba", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "MSC", local: "Cordoba Nuevo Centro", provincia: "Cordoba", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "MF2", local: "Florida 2", provincia: "Buenos Aires", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MCO", local: "Corrientes", provincia: "Buenos Aires", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MGP", local: "Galerias Pacifico", provincia: "Buenos Aires", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MC9", local: "Pellegrini", provincia: "Buenos Aires", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MPT", local: "Portal Tucuman", provincia: "Tucuman", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MDI", local: "Diagonal", provincia: "Buenos Aires", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MFL", local: "Florida 1", provincia: "Buenos Aires", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "MRM", local: "Recoleta Mall", provincia: "Buenos Aires", gerenteZona: "Erika Luna", gerenteRegion: "Pablo Baena" },
    { sigla: "MAP", local: "Alto Palermo", provincia: "Buenos Aires", gerenteZona: "Erika Luna", gerenteRegion: "Pablo Baena" },
    { sigla: "MAB", local: "Abasto", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MAC", local: "Acoyte", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MAT", local: "Mataderos", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MCJ", local: "Juan B Justo", provincia: "Buenos Aires", gerenteZona: "Erika Luna", gerenteRegion: "Pablo Baena" },
    { sigla: "MJS", local: "Trenes", provincia: "Buenos Aires", gerenteZona: "Erika Luna", gerenteRegion: "Pablo Baena" },
    { sigla: "MPB", local: "Parque Brown", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MMP", local: "Posadas", provincia: "Misiones", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MVC", local: "Village Caballito", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MIA", local: "Isla Abasto", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "MPC", local: "Parque Centenario", provincia: "Buenos Aires", gerenteZona: "Erika Luna", gerenteRegion: "Pablo Baena" },
    { sigla: "MML", local: "Lujan de Cuyo", provincia: "Mendoza", gerenteZona: "Guillermina Garis", gerenteRegion: "Gimena Conte" },
    { sigla: "MBM", local: "Barraca Mall", provincia: "Mendoza", gerenteZona: "Guillermina Garis", gerenteRegion: "Gimena Conte" },
    { sigla: "MMZ", local: "Mendoza", provincia: "Mendoza", gerenteZona: "Guillermina Garis", gerenteRegion: "Gimena Conte" },
    { sigla: "MWG", local: "Guaymallen", provincia: "Mendoza", gerenteZona: "Guillermina Garis", gerenteRegion: "Gimena Conte" },
    { sigla: "MGC", local: "Gonzalez Catan", provincia: "Buenos Aires", gerenteZona: "Antonella Horna", gerenteRegion: "Gimena Conte" },
    { sigla: "MTA", local: "Tablada", provincia: "Buenos Aires", gerenteZona: "Antonella Horna", gerenteRegion: "Gimena Conte" },
    { sigla: "MCS", local: "Carr San Justo", provincia: "Buenos Aires", gerenteZona: "Antonella Horna", gerenteRegion: "Gimena Conte" },
    { sigla: "MEP", local: "Parana Entre Rios", provincia: "Entre Ríos", gerenteZona: "Romina Bina", gerenteRegion: "Gimena Conte" },
    { sigla: "MWS", local: "Walmart San Justo", provincia: "Buenos Aires", gerenteZona: "Antonella Horna", gerenteRegion: "Gimena Conte" },
    { sigla: "MSJ", local: "San Justo 1", provincia: "Buenos Aires", gerenteZona: "Antonella Horna", gerenteRegion: "Gimena Conte" },
    { sigla: "MPO", local: "Plaza Oeste", provincia: "Buenos Aires", gerenteZona: "Milagros Sanchez", gerenteRegion: "Gimena Conte" },
    { sigla: "MNI", local: "Nine", provincia: "Buenos Aires", gerenteZona: "Romina Bina", gerenteRegion: "Gimena Conte" },
    { sigla: "MCM", local: "Carr Moreno", provincia: "Buenos Aires", gerenteZona: "Romina Bina", gerenteRegion: "Gimena Conte" },
    { sigla: "MMH", local: "Makro Haedo", provincia: "Buenos Aires", gerenteZona: "Milagros Sanchez", gerenteRegion: "Gimena Conte" },
    { sigla: "MLE", local: "Parque Leloir", provincia: "Buenos Aires", gerenteZona: "Milagros Sanchez", gerenteRegion: "Gimena Conte" },
    { sigla: "MLU", local: "Lujan 2", provincia: "Buenos Aires", gerenteZona: "Milagros Sanchez", gerenteRegion: "Gimena Conte" },
    { sigla: "MSN", local: "Salta Noa", provincia: "Salta", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MPA", local: "Panamericana", provincia: "Buenos Aires", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MDV", local: "Devoto", provincia: "Buenos Aires", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MUN", local: "Unicenter", provincia: "Buenos Aires", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MCB", local: "Caseros", provincia: "Buenos Aires", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MTC", local: "Tigre", provincia: "Buenos Aires", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MPF", local: "Puerto De Frutos", provincia: "Buenos Aires", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MAE", local: "Aeroparque", provincia: "Buenos Aires", gerenteZona: "Julieta Ochoa", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MDO", local: "Dot", provincia: "Buenos Aires", gerenteZona: "Julieta Ochoa", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MVL", local: "Vicente Lopez", provincia: "Buenos Aires", gerenteZona: "Julieta Ochoa", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MAR", local: "Alto Rosario", provincia: "Santa Fe", gerenteZona: "Milagros Sanchez", gerenteRegion: "Gimena Conte" },
    { sigla: "MVZ", local: "Velez", provincia: "Buenos Aires", gerenteZona: "Julieta Ochoa", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MCR", local: "City Center Rosario", provincia: "Santa Fe", gerenteZona: "Milagros Sanchez", gerenteRegion: "Gimena Conte" },
    { sigla: "MST", local: "San Martin 1", provincia: "Buenos Aires", gerenteZona: "Julieta Ochoa", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MCW", local: "Warnes", provincia: "Buenos Aires", gerenteZona: "Julieta Ochoa", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MSF", local: "Soleil", provincia: "Buenos Aires", gerenteZona: "Micaela Moreno", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MOT", local: "Tortugas", provincia: "Buenos Aires", gerenteZona: "Micaela Moreno", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MSM", local: "San Miguel 1", provincia: "Buenos Aires", gerenteZona: "Romina Bina", gerenteRegion: "Gimena Conte" },
    { sigla: "MNC", local: "Norcenter", provincia: "Buenos Aires", gerenteZona: "Micaela Moreno", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MCT", local: "Constituyentes", provincia: "Buenos Aires", gerenteZona: "Micaela Moreno", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MBP", local: "Pacheco", provincia: "Buenos Aires", gerenteZona: "Micaela Moreno", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MPP", local: "Paseo Pilar", provincia: "Buenos Aires", gerenteZona: "Micaela Moreno", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MNQ", local: "Neuquen", provincia: "Neuquen", gerenteZona: "Johana Gonzalez", gerenteRegion: "Gimena Conte" },
    { sigla: "MWN", local: "Walmart Neuquen", provincia: "Neuquen", gerenteZona: "Johana Gonzalez", gerenteRegion: "Gimena Conte" },
    { sigla: "MLA", local: "La Anonima", provincia: "Neuquen", gerenteZona: "Johana Gonzalez", gerenteRegion: "Gimena Conte" },
    { sigla: "MNA", local: "Alto Comahue", provincia: "Neuquen", gerenteZona: "Johana Gonzalez", gerenteRegion: "Gimena Conte" },
    { sigla: "MAN", local: "Neuquen Auto", provincia: "Neuquen", gerenteZona: "Johana Gonzalez", gerenteRegion: "Gimena Conte" },
    { sigla: "FLIN", local: "Liniers", provincia: "Buenos Aires", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FRAM", local: "Ramos", provincia: "Buenos Aires", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FMOR", local: "Moron 2", provincia: "Buenos Aires", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FCAS", local: "Castelar", provincia: "Buenos Aires", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FITU", local: "Ituzaingo", provincia: "Buenos Aires", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FLRJ", local: "La Rioja", provincia: "La Rioja", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FCAT", local: "Catamarca", provincia: "Catamarca", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FEZE", local: "Ezeiza", provincia: "Buenos Aires", gerenteZona: "Micaela Pardo", gerenteRegion: "Martin Medina" },
    { sigla: "FMGD", local: "Monte Grande", provincia: "Buenos Aires", gerenteZona: "Micaela Pardo", gerenteRegion: "Martin Medina" },
    { sigla: "FCAN", local: "Canning", provincia: "Buenos Aires", gerenteZona: "Micaela Pardo", gerenteRegion: "Martin Medina" },
    { sigla: "FSJU", local: "San Justo 3", provincia: "Buenos Aires", gerenteZona: "Micaela Pardo", gerenteRegion: "Martin Medina" },
    { sigla: "FLF2", local: "Laferrere 2", provincia: "Buenos Aires", gerenteZona: "Micaela Pardo", gerenteRegion: "Martin Medina" },
    { sigla: "FJUJ", local: "Jujuy", provincia: "Jujuy", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FSAO", local: "Salta Oran", provincia: "Salta", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FTU2", local: "Tucuman 2", provincia: "Tucuman", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FTU3", local: "Tucuman 3", provincia: "Tucuman", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FTU4", local: "Tucuman 4", provincia: "Tucuman", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FTU5", local: "Tucuman 5", provincia: "Tucuman", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FTU6", local: "Tucuman 6", provincia: "Tucuman", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FTU7", local: "Tucuman 7", provincia: "Tucuman", gerenteZona: "Rocio Fernandez", gerenteRegion: "Martin Medina" },
    { sigla: "FPSA", local: "Portal Salta", provincia: "Salta", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FSLI", local: "Salta Libertad", provincia: "Salta", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FSVP", local: "Salta Peatonal", provincia: "Salta", gerenteZona: "Gabriela Casas", gerenteRegion: "Martin Medina" },
    { sigla: "FMPRI", local: "Primera Junta", provincia: "Buenos Aires", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FFLO", local: "Flores", provincia: "Buenos Aires", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FPCH", local: "Parque Chacabuco", provincia: "Buenos Aires", gerenteZona: "Aylen Perez", gerenteRegion: "Hernan Dalto" },
    { sigla: "FPOM", local: "Pompeya", provincia: "Buenos Aires", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FSTM", local: "San Telmo", provincia: "Buenos Aires", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FLPA", local: "La Pampa", provincia: "La Pampa", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "MON", local: "Once", provincia: "Buenos Aires", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FPPI", local: "Palmas Del Pilar", provincia: "Buenos Aires", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FCAB", local: "Cabildo", provincia: "Buenos Aires", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FMCYM", local: "Cabildo 2", provincia: "Buenos Aires", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FSAF", local: "San Fernando", provincia: "Buenos Aires", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FMSMA", local: "San Miguel Auto", provincia: "Buenos Aires", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "F3DF", local: "San Martin Auto", provincia: "Buenos Aires", gerenteZona: "Iris Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FNQN", local: "Neuquen Centro", provincia: "Neuquen", gerenteZona: "Johana Gonzalez", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FMP2", local: "Paseo Aldrey", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FMP1", local: "Los Gallegos", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FMP3", local: "La Perla", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FMP4", local: "Mar del plata Peatonal", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FBOL", local: "Bolivar", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FCTA", local: "Tandil", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FOLA", local: "Olavarria", provincia: "Buenos Aires", gerenteZona: "Mayra Illuminati", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FRDN", local: "Rep De Los Niños", provincia: "Buenos Aires", gerenteZona: "Marisa Aranda", gerenteRegion: "Hernan Dalto" },
    { sigla: "FBER", local: "Berazategui", provincia: "Buenos Aires", gerenteZona: "Rocio Correa", gerenteRegion: "Hernan Dalto" },
    { sigla: "FGON", local: "Gonnet", provincia: "Buenos Aires", gerenteZona: "Marisa Aranda", gerenteRegion: "Hernan Dalto" },
    { sigla: "FROG", local: "Rotonda Gutierrez", provincia: "Buenos Aires", gerenteZona: "Marisa Aranda", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLOZ", local: "Lomas", provincia: "Buenos Aires", gerenteZona: "Rocio Correa", gerenteRegion: "Hernan Dalto" },
    { sigla: "FSJN", local: "San Juan 1", provincia: "San Juan", gerenteZona: "Marisa Aranda", gerenteRegion: "Hernan Dalto" },
    { sigla: "FSJ2", local: "San Juan 2", provincia: "San Juan", gerenteZona: "Marisa Aranda", gerenteRegion: "Hernan Dalto" },
    { sigla: "FMMSM", local: "Mendoza Peatonal", provincia: "Mendoza", gerenteZona: "Rocio Correa", gerenteRegion: "Hernan Dalto" },
    { sigla: "FMMCO", local: "Mendoza Colon", provincia: "Mendoza", gerenteZona: "Rocio Correa", gerenteRegion: "Hernan Dalto" },
    { sigla: "FQUP", local: "Quilmes Peatonal", provincia: "Buenos Aires", gerenteZona: "Ailen Perez", gerenteRegion: "Hernan Dalto" },
    { sigla: "FCQU", local: "Carr Quilmes", provincia: "Buenos Aires", gerenteZona: "Rocio Correa", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLAU", local: "Lanus Auto", provincia: "Buenos Aires", gerenteZona: "Ailen Perez", gerenteRegion: "Hernan Dalto" },
    { sigla: "FAVE", local: "Avellaneda", provincia: "Buenos Aires", gerenteZona: "Rocio Correa", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLA2", local: "Lanus 2", provincia: "Buenos Aires", gerenteZona: "Ailen Perez", gerenteRegion: "Hernan Dalto" },
    { sigla: "FRGA", local: "Rio Gallegos", provincia: "Santa Cruz", gerenteZona: "Ailen Perez", gerenteRegion: "Hernan Dalto" },
    { sigla: "FSRM", local: "San Rafael", provincia: "Mendoza", gerenteZona: "Ailen Perez", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLP2", local: "La Plata 2", provincia: "Buenos Aires", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLP3", local: "La Plata 3", provincia: "Buenos Aires", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLP4", local: "La Plata 4", provincia: "Buenos Aires", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLP5", local: "La Plata 5", provincia: "Buenos Aires", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FLP6", local: "La Plata 6", provincia: "Buenos Aires", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FCYB", local: "City Bell", provincia: "Buenos Aires", gerenteZona: "Marisa Aranda", gerenteRegion: "Hernan Dalto" },
    { sigla: "FRGD", local: "Rio Grande", provincia: "Tierra del Fuego", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FUSH", local: "Ushuaia", provincia: "Ushuaia", gerenteZona: "Elisabet Gassman", gerenteRegion: "Hernan Dalto" },
    { sigla: "FPRO", local: "Portal Rosario", provincia: "Santa Fe", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "FPEL", local: "Rosario Pellegrini", provincia: "Santa Fe", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "FRSM", local: "Rosario Sur", provincia: "Santa Fe", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "FORO", local: "Rosario Oroño", provincia: "Santa Fe", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "FSAN", local: "San Nicolas", provincia: "Buenos Aires", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "FPAR", local: "Parana", provincia: "Entre Ríos", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FRSF", local: "Ribera Santa Fe", provincia: "Santa Fe", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FRAF", local: "Rafaela", provincia: "Santa Fe", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FWSF", local: "Walmart Santa Fe", provincia: "Santa Fe", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FSFP", local: "Santa Fe Peatonal", provincia: "Santa Fe", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FAVM", local: "Av De Mayo 1", provincia: "Buenos Aires", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FAV2", local: "Av De Mayo 2", provincia: "Buenos Aires", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FBOE", local: "Boedo", provincia: "Buenos Aires", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "F9DJ", local: "9 De Julio", provincia: "Buenos Aires", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FCAL", local: "Callao", provincia: "Buenos Aires", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FSLS", local: "San Luis", provincia: "San Luis", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FLUJ", local: "Lujan", provincia: "Buenos Aires", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FMNO", local: "Moreno", provincia: "Buenos Aires", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FFRA", local: "Francisco Alvarez", provincia: "Buenos Aires", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FMER", local: "Merlo", provincia: "Buenos Aires", gerenteZona: "Marina Gonzalez", gerenteRegion: "Melisa Castillo" },
    { sigla: "FSDE", local: "Santiago Del Estero", provincia: "Santiago del Estero", gerenteZona: "Ranquel Pereiro", gerenteRegion: "Melisa Castillo" },
    { sigla: "FCOR", local: "Corrientes 1", provincia: "Corrientes", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FRES", local: "Resistencia", provincia: "Chaco", gerenteZona: "Sabrina Peralta", gerenteRegion: "Melisa Castillo" },
    { sigla: "FJCP", local: "Jose C Paz", provincia: "Buenos Aires", gerenteZona: "Ranquel Pereiro", gerenteRegion: "Melisa Castillo" },
    { sigla: "FGBG", local: "Grand Bourg", provincia: "Buenos Aires", gerenteZona: "Ranquel Pereiro", gerenteRegion: "Melisa Castillo" },
    { sigla: "FGUE", local: "Guemes", provincia: "Buenos Aires", gerenteZona: "Ranquel Pereiro", gerenteRegion: "Melisa Castillo" },
    { sigla: "FURQ", local: "Urquiza", provincia: "Buenos Aires", gerenteZona: "Ranquel Pereiro", gerenteRegion: "Melisa Castillo" },
    { sigla: "FSPI", local: "Spinetto", provincia: "Buenos Aires", gerenteZona: "Ranquel Pereiro", gerenteRegion: "Melisa Castillo" },
    { sigla: "FPES", local: "Plaza España", provincia: "Buenos Aires", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "FVCP", local: "Carlos Paz", provincia: "Cordoba", gerenteZona: "Sabrina Orlando", gerenteRegion: "Melisa Castillo" },
    { sigla: "UCU", local: "Costa Urbana", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "ULP", local: "Las Piedras", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "UMI", local: "Minas", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "UNC", local: "Nuevo Centro", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "UPC", local: "Punta Carretas", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "UPE", local: "Punta Del Este", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "UPS", local: "Punta del Este Shopping", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "UTC", local: "Tres Cruces", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "FUCA", local: "Agraciada", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "FU19", local: "18 y rio branco", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Andrea Escobar" },
    { sigla: "UMO", local: "Rivera y Herrera", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Esteban De Oliveira" },
    { sigla: "FU18", local: "18 De Julio", provincia: "Exterior", gerenteZona: "Andrea Escobar", gerenteRegion: "Andrea Escobar" },
    { sigla: "FFOR", local: "Formosa", provincia: "Interior", gerenteZona: "Raul Ayala", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "OFI", local: "Oficinas", provincia: "Buenos Aires", gerenteZona: "Daniel Rossano", gerenteRegion: "Daniel Rossano" },
    { sigla: "MLC", local: "Avenida La Plata", provincia: "Buenos Aires", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "FBA1", local: "Bariloche 1", provincia: "Rio Negro", gerenteZona: "Hernan Dalto", gerenteRegion: "Hernan Dalto" },
    { sigla: "FBME", local: "Megacenter", provincia: "Exterior", gerenteZona: "Sebastian Bruno", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FBVE", local: "Ventura", provincia: "Exterior", gerenteZona: "Sebastian Bruno", gerenteRegion: "Cecilia Riccadonna" },
    { sigla: "FPFT", local: "FoodTruck", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPFU", local: "Fuente", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPGA", local: "Galeria", provincia: "Exterior", gerenteZona: "Laura Acosta", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPLA", local: "Lago", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPMC", local: "Mariscal", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPMN", local: "Mariano", provincia: "Exterior", gerenteZona: "Laura Acosta", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPMP", local: "Multiplaza", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPMU", local: "Municipalidad", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPPD", local: "Pinedo", provincia: "Exterior", gerenteZona: "Laura Acosta", gerenteRegion: "Micaela Pardo" },
    { sigla: "FPSL", local: "Sol", provincia: "Exterior", gerenteZona: "Laura Acosta", gerenteRegion: "Micaela Pardo" },
    { sigla: "MMC", local: "Posadas 2", provincia: "Misiones", gerenteZona: "Pablo Cozzo", gerenteRegion: "Pablo Baena" },
    { sigla: "FPSL", local: "San Lorenzo", provincia: "Exterior", gerenteZona: "Laura Acosta", gerenteRegion: "Micaela Pardo" },
    { sigla: "MCH", local: "Comodoro Auto", provincia: "Interior", gerenteZona: "Bruno Ureta", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MAM", local: "Arena Maipu", provincia: "Interior", gerenteZona: "Guillermina Garis", gerenteRegion: "Gimena Conte" },
    { sigla: "MT1", local: "Pinamar", provincia: "Interior", gerenteZona: "Joaquin Aquino", gerenteRegion: "Pablo Baena" },
    { sigla: "FTU8", local: "Tucuman 8", provincia: "Tucuman", gerenteZona: "Rocio Hernandez", gerenteRegion: "Martin Medina" },
    { sigla: "MPAT", local: "Panamericana Auto", provincia: "", gerenteZona: "Sofia Sas", gerenteRegion: "Alejandro Alvarez" },
    { sigla: "MSB", local: "Bahia Shopping", provincia: "Interior", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MLZ", local: "Lomas Centro", provincia: "Buenos Aires", gerenteZona: "Romina De Luca", gerenteRegion: "Jesica Espinoza" },
    { sigla: "MRC", local: "Rio Cuarto", provincia: "Interior", gerenteZona: "Laura Zapana", gerenteRegion: "Pablo Baena" },
    { sigla: "FSANB", local: "San Bernardino", provincia: "Exterior", gerenteZona: "Jorge Yennison", gerenteRegion: "Micaela Pardo" }
];